In [153]:
import torch
import numpy as np

In [154]:
pip install torch


Note: you may need to restart the kernel to use updated packages.


## Empty Tensor

In [156]:
x = torch.empty(5, 3)
print(x)

tensor([[1.4013e-45, 0.0000e+00, 1.4013e-45],
        [0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


## Random Tensor

In [157]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0956, 0.3855, 0.8117],
        [0.7673, 0.1492, 0.1206],
        [0.6585, 0.1558, 0.6740],
        [0.6181, 0.2249, 0.3646],
        [0.8299, 0.6593, 0.6405]])


## Zero Tensor

In [159]:
x = torch.zeros(5, 8, dtype=torch.int)
print(x)

tensor([[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]], dtype=torch.int32)


## Manually enter the numbers

In [160]:
x = torch.tensor([[5.5, 3],  [4.4,10.1],  [5.1, 5.2], [2,2]])
print(x)

tensor([[ 5.5000,  3.0000],
        [ 4.4000, 10.1000],
        [ 5.1000,  5.2000],
        [ 2.0000,  2.0000]])


## Tensor like Another one

In [162]:
y = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(y)  

tensor([[-0.2247, -0.8448],
        [ 0.9171,  1.4780],
        [-2.3214, -0.4004],
        [ 0.6851, -1.6463]])


In [164]:
y.shape

torch.Size([4, 2])

In [165]:
y.size()

torch.Size([4, 2])

## Additions (like Matrix Addition)

In [189]:
y = torch.ones(5, 3)
x = torch.ones(5,3)


In [190]:
print(x);print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [191]:
print(x + y)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [192]:
torch.add(x, y)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [193]:
result = torch.zeros_like(x)
torch.add(x, y, out=result)
print(result)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


## Shape and VIEW

In [194]:
x.shape

torch.Size([5, 3])

In [195]:
x.view(1,15)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [196]:
x.view(3,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [197]:
x.view(15,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [198]:
x.view(-1, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [203]:
x.view(3, -1)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [178]:
y=   x.view(1, -1)
print(y)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [181]:
x = torch.randn(1)
print(x)

tensor([0.1842])


In [183]:
x[0].item()

0.18418528139591217

## Convert to Numpy and Vice Versa

In [210]:
x=torch.ones(5,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [211]:
y = x.numpy()


In [212]:
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [214]:
type(y)

numpy.ndarray

In [215]:
import numpy as np
a = np.array([[3,4],[5,6],[7,8]])


In [217]:
a

array([[3, 4],
       [5, 6],
       [7, 8]])

In [218]:
b = torch.from_numpy(a)


In [220]:
print(b)

tensor([[3, 4],
        [5, 6],
        [7, 8]], dtype=torch.int32)


## RUN ON GPU

In [221]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)    

In [223]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [224]:
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

## More about Dimensions

In [248]:
a= torch.randn(5,4)

In [249]:
print(a)

tensor([[ 0.9360, -0.4312,  0.0257,  1.1298],
        [-1.0834,  0.6004, -0.5439,  0.3076],
        [-0.4867, -0.3191,  0.4387,  0.1758],
        [ 1.4237, -0.1179, -0.5174, -1.3562],
        [ 0.0987, -1.1699, -0.4249, -0.6130]])


In [250]:
a.shape

torch.Size([5, 4])

In [252]:
a[0,:]

tensor([ 0.9360, -0.4312,  0.0257,  1.1298])

In [253]:
a[:,0]

tensor([ 0.9360, -1.0834, -0.4867,  1.4237,  0.0987])

In [254]:
a[2]

tensor([-0.4867, -0.3191,  0.4387,  0.1758])

In [260]:
b=a.unsqueeze(1)

In [261]:
b.shape

torch.Size([5, 1, 4])

In [262]:
print(b)

tensor([[[ 0.9360, -0.4312,  0.0257,  1.1298]],

        [[-1.0834,  0.6004, -0.5439,  0.3076]],

        [[-0.4867, -0.3191,  0.4387,  0.1758]],

        [[ 1.4237, -0.1179, -0.5174, -1.3562]],

        [[ 0.0987, -1.1699, -0.4249, -0.6130]]])


In [263]:
c=b.unsqueeze(0)

In [264]:
c.shape

torch.Size([1, 5, 1, 4])

In [265]:
d=c.squeeze(0)

In [266]:
d.shape

torch.Size([5, 1, 4])

In [267]:
d=d.squeeze(0)

In [268]:
d.shape

torch.Size([5, 1, 4])

## Matrix Multiplication

In [271]:
%%time
a=np.random.randn(2000,2000)
b=np.random.randn(2000,2000)
c=np.matmul(a,b)

Wall time: 274 ms


In [273]:
%%time
a=torch.randn([2000,2000]).to(device)
b=torch.randn([2000,2000]).to(device)
c=torch.matmul(a,b)

Wall time: 84.1 ms


## Gradients

In [287]:
x = torch.ones(3,2, requires_grad=True)

In [288]:
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)

In [289]:
y=x+5
z=y*y+7

In [290]:
print(z)

tensor([[43., 43.],
        [43., 43.],
        [43., 43.]], grad_fn=<AddBackward0>)


In [291]:
t=torch.sum(z)

In [292]:
t

tensor(258., grad_fn=<SumBackward0>)

In [293]:
t.backward()

Dt/dx

In [294]:
print(t)

tensor(258., grad_fn=<SumBackward0>)


In [295]:
print(z.grad)

None


In [296]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


## d {((x+5)**2 +7)}/d{x} =====>2*(x+5)==>12 

In [297]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


In [298]:
x=torch.tensor([2,2,4,5,5,7,9,10])

In [299]:
y=torch.tensor([2,2,4,5,5,8,10,9])

In [300]:
print(x.eq(y))

tensor([ True,  True,  True,  True,  True, False, False, False])


In [301]:
x.eq(y).sum()

tensor(5)